# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.0'

gem 'activesupport'
gem 'addressable'
gem 'browserstack-local'
gem 'capybara'
gem 'capybara-extensions'
gem 'capybara-screenshot'
gem 'cld2', require: 'cld', git: 'https://github.com/Alpenglow88/cld2.git'
gem 'cucumber'
gem 'geckodriver-helper'
gem 'mail'
gem 'parallel'
gem 'parallel_tests'
gem 'parser'
gem 'pry'
gem 'rake'
gem 'report_builder'
gem 'require_all'
gem 'rest-client'
gem 'rspec'
gem 'rubocop', '~> 1.11.0'
gem 'rubocop-performance'
gem 'selenium-webdriver', '3.142.3'
gem 'simplecov'
gem 'site_prism'
gem 'solargraph'
gem 'webdrivers'
